### ISSUE TITLE
Update to css for small factor mobile

### ISSUE THREAD

**Issue by camakin** [smartnodescc/smartnodescc.github.io#1]
Updated jumbotron headers in css to allow for small factor mobile.
Also missing brace } on line 86 which threw me off :)

line 84 down ->

`
.row {
  background-position: 0 -30%;
}
/* Custom page footer */
.footer {
  padding-top: 194px;
  color: #777;
  border-top: 1px solid #e5e5e5;
}

/* Customize container */
@media (min-width: 768px) {
  .container {
    max-width: 730px;
  }
}
.container-narrow > hr {
  margin: 30px 0;
}

.jumbotron {
  text-align: center;
  border-bottom: 1px solid #e5e5e5;
}
.jumbotron .btn {
  padding: 14px 24px;
  font-size: 21px;
}

/* Responsive: Portrait tablets and up */
@media screen and (min-width: 768px) {
  /* Remove the padding we set earlier */
  .header,
  .footer {
    padding-right: 0;
    padding-left: 0;
  }
  /* Space out the masthead */
  .header {
    margin-bottom: 30px;
  }
  /* Remove the bottom border on the jumbotron for visual effect */
  .jumbotron {
    border-bottom: 0;
  }
  .box {
    border-bottom: 0;
  }
}
	
@media screen and (min-width : 320px) { 
	/* STYLES GO HERE */
	.jumbotron h1 {
		font-size: 3em !important;
	}
	.jumbotron h2 {
		font-size: 2em !important;
	}
}

`

**Comment by nflaw** [comment]
camakin joined as contributor after invitation from me, proposed changes to css directly. Manually adopting code would be too time consuming. Changes adopted after review.
