### ISSUE TITLE
SmartNode on Windows Server VPS

### ISSUE THREAD

**Issue by bozzfozz** [smartnodescc/smartnodescc.github.io#6]
it can be synonymous determined man on windows server, if so how? For this is this smartnode.conf file necessary or?

**Comment by nflaw** [comment]
Hello,

For questions regarding the setup of a SmartNode please refer to one of our SmartCash support channels:
- [SmartCash forum](https://forum.smartcash.cc)
- [SmartCash support platform](https://smartcash.freshdesk.com)
- [#smartnodes on Discord](https://discord.gg/BDUh8jr)
- [SmartCash support on Twitter](https://twitter.com/smartcashassist)

**This Github is solely dedicated to development of the SmartNodes.cc website.**

Thank you and have a good day!
